package world.phantasmal.cliexporter

import world.phantasmal.psolib.fileFormats.ninja.*
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

/**
 * PSO uses 30 FPS for animations.
 */
private const val PSO_FRAME_RATE = 30.0

/**
 * FBX KTime units per second (46186158000 represents 1 second in KTime).
 */
private const val KTIME_PER_SECOND = 46186158000L

class FbxExporter {
    private var nextId = 100000L
    private val animStackId = 10000001L
    private val animLayerId = 10000002L
    
    // Track animation curve connections for linking in Connections section
    private data class CurveConnection(
        val curveNodeId: Long,
        val curveXId: Long,
        val curveYId: Long,
        val curveZId: Long,
        val boneId: Long,
        val channel: String // "T", "R", or "S"
    )
    private val curveConnections = mutableListOf<CurveConnection>()

    fun export(
        geometryObjects: List<NinjaObject<*, *>>,
        animation: NjMotion
    ): String {
        // Reset state for new export
        curveConnections.clear()
        
        if (geometryObjects.isEmpty()) {
            throw IllegalArgumentException("Geometry objects list is empty")
        }

        val rootObject = geometryObjects.first()
        val boneCount = rootObject.boneCount()

        // Validate animation has matching or fewer bones
        if (animation.motionData.size > boneCount) {
            println("Warning: Animation has ${animation.motionData.size} tracks but geometry has only $boneCount bones. Extra tracks will be ignored.")
        }

        val sb = StringBuilder()

        // Write header
        writeHeader(sb)

        // Write global settings
        writeGlobalSettings(sb)

        // Write documents
        writeDocuments(sb)

        // Collect bone information
        val bones = collectBones(rootObject)

        // Write objects
        writeObjects(sb, bones, animation)

        // Write connections
        writeConnections(sb, bones, animation)

        return sb.toString()
    }

    private fun writeHeader(sb: StringBuilder) {
        val now = LocalDateTime.now()
        val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss:SSS")

        sb.append("""
; FBX 7.4.0 project file
; Generated by Phantasmal World CLI Exporter
; Creation Time: ${now.format(formatter)}
; ----------------------------------------------------

FBXHeaderExtension:  {
    FBXHeaderVersion: 1003
    FBXVersion: 7400
    CreationTimeStamp:  {
        Version: 1000
        Year: ${now.year}
        Month: ${now.monthValue}
        Day: ${now.dayOfMonth}
        Hour: ${now.hour}
        Minute: ${now.minute}
        Second: ${now.second}
        Millisecond: ${now.nano / 1_000_000}
    }
    Creator: "Phantasmal World CLI Exporter 1.0"
    SceneInfo: "SceneInfo::GlobalInfo", "UserData" {
        Type: "UserData"
        Version: 100
        MetaData:  {
            Version: 100
            Title: ""
            Subject: ""
            Author: ""
            Keywords: ""
            Revision: ""
            Comment: ""
        }
    }
}

""".trimIndent())
    }

    private fun writeGlobalSettings(sb: StringBuilder) {
        sb.append("""
GlobalSettings:  {
    Version: 1000
    Properties70:  {
        P: "UpAxis", "int", "Integer", "",1
        P: "UpAxisSign", "int", "Integer", "",1
        P: "FrontAxis", "int", "Integer", "",2
        P: "FrontAxisSign", "int", "Integer", "",1
        P: "CoordAxis", "int", "Integer", "",0
        P: "CoordAxisSign", "int", "Integer", "",1
        P: "OriginalUpAxis", "int", "Integer", "",-1
        P: "OriginalUpAxisSign", "int", "Integer", "",1
        P: "UnitScaleFactor", "double", "Number", "",1
        P: "OriginalUnitScaleFactor", "double", "Number", "",1
        P: "AmbientColor", "ColorRGB", "Color", "",0,0,0
        P: "DefaultCamera", "KString", "", "", "Producer Perspective"
        P: "TimeMode", "enum", "", "",0
        P: "TimeProtocol", "enum", "", "",2
        P: "SnapOnFrameMode", "enum", "", "",0
        P: "TimeSpanStart", "KTime", "Time", "",0
        P: "TimeSpanStop", "KTime", "Time", "",46186158000
        P: "CustomFrameRate", "double", "Number", "",$PSO_FRAME_RATE
        P: "TimeMarker", "Compound", "", ""
        P: "CurrentTimeMarker", "int", "Integer", "",-1
    }
}

""".trimIndent())
    }

    private fun writeDocuments(sb: StringBuilder) {
        sb.append("""
Documents:  {
    Count: 1
    Document: 12345678, "", "Scene" {
        Properties70:  {
            P: "SourceObject", "object", "", ""
            P: "ActiveAnimStackName", "KString", "", "", "Take 001"
        }
        RootNode: 0
    }
}

""".trimIndent())
    }

    private data class BoneInfo(
        val index: Int,
        val id: Long,
        val name: String,
        val obj: NinjaObject<*, *>,
        val parentIndex: Int?
    )

    private fun collectBones(rootObject: NinjaObject<*, *>): List<BoneInfo> {
        val bones = mutableListOf<BoneInfo>()
        var boneIndex = 0

        fun traverseObject(obj: NinjaObject<*, *>, parentIndex: Int?): Unit {
            fun traverseChildren(currentParentIndex: Int?) {
                if (!obj.evaluationFlags.breakChildTrace) {
                    for (child in obj.children) {
                        traverseObject(child, currentParentIndex)
                    }
                }
            }

            if (!obj.evaluationFlags.skip) {
                val currentIndex = boneIndex++
                bones.add(
                    BoneInfo(
                        index = currentIndex,
                        id = nextId++,
                        name = "Bone_$currentIndex",
                        obj = obj,
                        parentIndex = parentIndex
                    )
                )
                traverseChildren(currentIndex)
            } else {
                // Still need to traverse children even if this node is skipped
                traverseChildren(parentIndex)
            }
        }

        traverseObject(rootObject, null)
        return bones
    }

    private fun writeObjects(sb: StringBuilder, bones: List<BoneInfo>, animation: NjMotion) {
        sb.append("Objects:  {\n")

        // Write bone models
        for (bone in bones) {
            writeBoneModel(sb, bone)
        }

        // Write animation curves
        writeAnimationCurves(sb, bones, animation)

        // Write animation stack
        sb.append("""
    AnimationStack: $animStackId, "AnimStack::Take 001", "" {
        Properties70:  {
            P: "LocalStart", "KTime", "Time", "",0
            P: "LocalStop", "KTime", "Time", "",${frameToKTime(animation.frameCount)}
            P: "ReferenceStart", "KTime", "Time", "",0
            P: "ReferenceStop", "KTime", "Time", "",${frameToKTime(animation.frameCount)}
        }
    }
    AnimationLayer: $animLayerId, "AnimLayer::BaseLayer", "" {
    }

""".trimIndent())

        sb.append("}\n\n")
    }

    private fun writeBoneModel(sb: StringBuilder, bone: BoneInfo) {
        val obj = bone.obj
        
        // Convert rotation from radians to degrees
        val rotX = Math.toDegrees(obj.rotation.x.toDouble())
        val rotY = Math.toDegrees(obj.rotation.y.toDouble())
        val rotZ = Math.toDegrees(obj.rotation.z.toDouble())

        sb.append("""
    Model: ${bone.id}, "Model::${bone.name}", "LimbNode" {
        Version: 232
        Properties70:  {
            P: "RotationActive", "bool", "", "",1
            P: "InheritType", "enum", "", "",1
            P: "ScalingMax", "Vector3D", "Vector", "",0,0,0
            P: "Lcl Translation", "Lcl Translation", "", "A",${obj.position.x},${obj.position.y},${obj.position.z}
            P: "Lcl Rotation", "Lcl Rotation", "", "A",$rotX,$rotY,$rotZ
            P: "Lcl Scaling", "Lcl Scaling", "", "A",${obj.scale.x},${obj.scale.y},${obj.scale.z}
        }
        Shading: T
        Culling: "CullingOff"
    }
""".trimIndent())
        sb.append("\n")
    }

    private fun writeAnimationCurves(sb: StringBuilder, bones: List<BoneInfo>, animation: NjMotion) {
        for (boneIndex in bones.indices) {
            if (boneIndex >= animation.motionData.size) {
                // No animation data for this bone
                continue
            }

            val motionData = animation.motionData[boneIndex]
            val bone = bones[boneIndex]

            for (track in motionData.tracks) {
                when (track) {
                    is NjKeyframeTrack.Position -> {
                        writeAnimationCurveNode(sb, bone, "T", track.keyframes, animation.interpolation, isRotation = false)
                    }
                    is NjKeyframeTrack.EulerAngles -> {
                        writeAnimationCurveNode(sb, bone, "R", track.keyframes, animation.interpolation, isRotation = true)
                    }
                    is NjKeyframeTrack.Scale -> {
                        writeAnimationCurveNode(sb, bone, "S", track.keyframes, animation.interpolation, isRotation = false)
                    }
                    is NjKeyframeTrack.Quaternion -> {
                        // Convert quaternion to euler angles for FBX
                        // For now, we'll skip quaternion tracks as they require complex conversion
                        println("Warning: Quaternion tracks are not yet supported, skipping for ${bone.name}")
                    }
                }
            }
        }
    }

    private fun writeAnimationCurveNode(
        sb: StringBuilder,
        bone: BoneInfo,
        channel: String, // "T", "R", or "S"
        keyframes: List<NjKeyframe.Vector>,
        interpolation: NjInterpolation,
        isRotation: Boolean
    ) {
        if (keyframes.isEmpty()) return

        val curveNodeId = nextId++
        val curveXId = nextId++
        val curveYId = nextId++
        val curveZId = nextId++

        // Track this connection for later use in Connections section
        curveConnections.add(
            CurveConnection(
                curveNodeId = curveNodeId,
                curveXId = curveXId,
                curveYId = curveYId,
                curveZId = curveZId,
                boneId = bone.id,
                channel = channel
            )
        )

        // Write AnimationCurveNode
        sb.append("""
    AnimationCurveNode: $curveNodeId, "AnimCurveNode::$channel", "" {
        Properties70:  {
            P: "d|X", "Number", "", "A",${if (isRotation) Math.toDegrees(keyframes[0].value.x.toDouble()) else keyframes[0].value.x}
            P: "d|Y", "Number", "", "A",${if (isRotation) Math.toDegrees(keyframes[0].value.y.toDouble()) else keyframes[0].value.y}
            P: "d|Z", "Number", "", "A",${if (isRotation) Math.toDegrees(keyframes[0].value.z.toDouble()) else keyframes[0].value.z}
        }
    }
""".trimIndent())
        sb.append("\n")

        // Write curves for X, Y, Z components
        writeSingleAnimationCurve(sb, curveXId, keyframes.map { it.frame to (if (isRotation) Math.toDegrees(it.value.x.toDouble()) else it.value.x.toDouble()) }, interpolation)
        writeSingleAnimationCurve(sb, curveYId, keyframes.map { it.frame to (if (isRotation) Math.toDegrees(it.value.y.toDouble()) else it.value.y.toDouble()) }, interpolation)
        writeSingleAnimationCurve(sb, curveZId, keyframes.map { it.frame to (if (isRotation) Math.toDegrees(it.value.z.toDouble()) else it.value.z.toDouble()) }, interpolation)
    }

    private fun writeSingleAnimationCurve(
        sb: StringBuilder,
        curveId: Long,
        keyframes: List<Pair<Int, Double>>, // frame to value
        interpolation: NjInterpolation
    ) {
        if (keyframes.isEmpty()) return

        val interpMode = when (interpolation) {
            NjInterpolation.Linear -> "linear"
            NjInterpolation.Spline -> "cubic"
            NjInterpolation.UserFunction -> "linear" // Fallback
        }

        val times = keyframes.joinToString(",") { frameToKTime(it.first).toString() }
        val values = keyframes.joinToString(",") { "%.6f".format(it.second) }
        
        sb.append("""
    AnimationCurve: $curveId, "AnimCurve::", "" {
        Default: 0
        KeyVer: 4009
        KeyTime: $times
        KeyValueFloat: $values
        KeyAttrFlags: ${keyframes.joinToString(",") { "24836" }}
        KeyAttrDataFloat: ${keyframes.joinToString(",") { "0,0,9.419963346924634e-30,0" }}
        KeyAttrRefCount: ${keyframes.joinToString(",") { "1" }}
    }
""".trimIndent())
        sb.append("\n")
    }

    private fun frameToKTime(frame: Int): Long {
        return (frame.toDouble() / PSO_FRAME_RATE * KTIME_PER_SECOND).toLong()
    }

    private fun writeConnections(sb: StringBuilder, bones: List<BoneInfo>, animation: NjMotion) {
        sb.append("Connections:  {\n")

        // Connect bones to their parents
        for (bone in bones) {
            if (bone.parentIndex != null) {
                val parent = bones[bone.parentIndex]
                sb.append("    ;Model::${bone.name}, Model::${parent.name}\n")
                sb.append("    C: \"OO\",${bone.id},${parent.id}\n\n")
            }
        }

        // Connect animation layer to animation stack
        sb.append("    ;AnimLayer::BaseLayer, AnimStack::Take 001\n")
        sb.append("    C: \"OO\",$animLayerId,$animStackId\n\n")

        // Connect animation curve nodes to bones and animation layer
        for (connection in curveConnections) {
            // Connect curve node to bone's property
            val property = when (connection.channel) {
                "T" -> "Lcl Translation"
                "R" -> "Lcl Rotation"
                "S" -> "Lcl Scaling"
                else -> connection.channel
            }
            sb.append("    ;AnimCurveNode::${connection.channel}, Model::Bone_${bones.find { it.id == connection.boneId }?.index}\n")
            sb.append("    C: \"OP\",${connection.curveNodeId},${connection.boneId}, \"$property\"\n\n")

            // Connect curve node to animation layer
            sb.append("    ;AnimCurveNode::${connection.channel}, AnimLayer::BaseLayer\n")
            sb.append("    C: \"OO\",${connection.curveNodeId},$animLayerId\n\n")

            // Connect individual curves (X, Y, Z) to the curve node
            sb.append("    ;AnimCurve::, AnimCurveNode::${connection.channel}\n")
            sb.append("    C: \"OP\",${connection.curveXId},${connection.curveNodeId}, \"d|X\"\n")
            sb.append("    C: \"OP\",${connection.curveYId},${connection.curveNodeId}, \"d|Y\"\n")
            sb.append("    C: \"OP\",${connection.curveZId},${connection.curveNodeId}, \"d|Z\"\n\n")
        }

        sb.append("}\n\n")
    }
}
