package world.phantasmal.cliexporter

import world.phantasmal.psolib.fileFormats.ninja.*
import java.io.File
import java.io.PrintWriter

/**
 * Exports PSO animations to FBX ASCII format (version 7.4.0).
 * PSO uses 30 FPS frame rate.
 */
object FbxExporter {
    private const val PSO_FRAME_RATE = 30.0
    private const val KTIME_PER_SECOND = 46186158000L
    
    fun export(ninjaObject: NinjaObject<*, *>, motion: NjMotion, outputFile: File) {
        PrintWriter(outputFile).use { writer ->
            writeHeader(writer)
            writeGlobalSettings(writer, motion)
            writeDocuments(writer)
            writeDefinitions(writer, ninjaObject.boneCount(), motion)
            val curveIds = writeObjects(writer, ninjaObject, motion)
            writeConnections(writer, ninjaObject, motion, curveIds)
        }
    }
    
    private fun writeHeader(writer: PrintWriter) {
        writer.println("; FBX 7.4.0 project file")
        writer.println("; Generated by Phantasmal World CLI Exporter")
        writer.println("; ----------------------------------------------------")
        writer.println()
        writer.println("FBXHeaderExtension:  {")
        writer.println("    FBXHeaderVersion: 1003")
        writer.println("    FBXVersion: 7400")
        writer.println("    Creator: \"Phantasmal World CLI Exporter\"")
        writer.println("}")
        writer.println()
    }
    
    private fun writeGlobalSettings(writer: PrintWriter, motion: NjMotion) {
        writer.println("GlobalSettings:  {")
        writer.println("    Version: 1000")
        writer.println("    Properties70:  {")
        writer.println("        P: \"UpAxis\", \"int\", \"Integer\", \"\",1")
        writer.println("        P: \"UpAxisSign\", \"int\", \"Integer\", \"\",1")
        writer.println("        P: \"FrontAxis\", \"int\", \"Integer\", \"\",2")
        writer.println("        P: \"FrontAxisSign\", \"int\", \"Integer\", \"\",1")
        writer.println("        P: \"CoordAxis\", \"int\", \"Integer\", \"\",0")
        writer.println("        P: \"CoordAxisSign\", \"int\", \"Integer\", \"\",1")
        writer.println("        P: \"OriginalUpAxis\", \"int\", \"Integer\", \"\",1")
        writer.println("        P: \"OriginalUpAxisSign\", \"int\", \"Integer\", \"\",1")
        writer.println("        P: \"UnitScaleFactor\", \"double\", \"Number\", \"\",1")
        writer.println("        P: \"OriginalUnitScaleFactor\", \"double\", \"Number\", \"\",1")
        writer.println("        P: \"TimeSpanStart\", \"KTime\", \"Time\", \"\",0")
        writer.println("        P: \"TimeSpanStop\", \"KTime\", \"Time\", \"\",${frameToKTime(motion.frameCount - 1)}")
        writer.println("        P: \"CustomFrameRate\", \"double\", \"Number\", \"\",$PSO_FRAME_RATE")
        writer.println("    }")
        writer.println("}")
        writer.println()
    }
    
    private fun writeDocuments(writer: PrintWriter) {
        writer.println("Documents:  {")
        writer.println("    Count: 1")
        writer.println("    Document: 1234567890, \"\", \"Scene\" {")
        writer.println("        Properties70:  {")
        writer.println("        }")
        writer.println("        RootNode: 0")
        writer.println("    }")
        writer.println("}")
        writer.println()
    }
    
    private fun writeDefinitions(writer: PrintWriter, boneCount: Int, motion: NjMotion) {
        writer.println("Definitions:  {")
        writer.println("    Version: 100")
        writer.println("    Count: 4")
        writer.println("    ObjectType: \"Model\" {")
        writer.println("        Count: $boneCount")
        writer.println("    }")
        writer.println("    ObjectType: \"AnimationStack\" {")
        writer.println("        Count: 1")
        writer.println("    }")
        writer.println("    ObjectType: \"AnimationLayer\" {")
        writer.println("        Count: 1")
        writer.println("    }")
        writer.println("    ObjectType: \"AnimationCurveNode\" {")
        writer.println("        Count: ${motion.motionData.size * 3}") // Approximate
        writer.println("    }")
        writer.println("}")
        writer.println()
    }
    
    private fun writeObjects(writer: PrintWriter, ninjaObject: NinjaObject<*, *>, motion: NjMotion): Pair<Long, Long> {
        writer.println("Objects:  {")
        
        // Write bone models
        val boneIndices = mutableMapOf<NinjaObject<*, *>, Int>()
        writeBoneModels(writer, ninjaObject, boneIndices, -1)
        
        // Write animation stack
        writer.println("    AnimationStack: 2345678901, \"AnimStack::Take 001\", \"\" {")
        writer.println("        Properties70:  {")
        writer.println("            P: \"LocalStart\", \"KTime\", \"Time\", \"\",0")
        writer.println("            P: \"LocalStop\", \"KTime\", \"Time\", \"\",${frameToKTime(motion.frameCount - 1)}")
        writer.println("            P: \"ReferenceStart\", \"KTime\", \"Time\", \"\",0")
        writer.println("            P: \"ReferenceStop\", \"KTime\", \"Time\", \"\",${frameToKTime(motion.frameCount - 1)}")
        writer.println("        }")
        writer.println("    }")
        writer.println()
        
        // Write animation layer
        writer.println("    AnimationLayer: 3456789012, \"AnimLayer::BaseLayer\", \"\" {")
        writer.println("    }")
        writer.println()
        
        // Write animation curves for each bone
        val curveIds = writeAnimationCurves(writer, ninjaObject, motion, boneIndices)
        
        writer.println("}")
        writer.println()
        
        return curveIds
    }
    
    private fun writeBoneModels(
        writer: PrintWriter,
        obj: NinjaObject<*, *>,
        boneIndices: MutableMap<NinjaObject<*, *>, Int>,
        parentIndex: Int
    ): Int {
        if (obj.evaluationFlags.skip) {
            // Process children but don't create a bone for this object
            for (child in obj.children) {
                writeBoneModels(writer, child, boneIndices, parentIndex)
            }
            return parentIndex
        }
        
        val boneIndex = boneIndices.size
        boneIndices[obj] = boneIndex
        val modelId = 1000000000L + boneIndex
        
        writer.println("    Model: $modelId, \"Model::Bone_$boneIndex\", \"LimbNode\" {")
        writer.println("        Version: 232")
        writer.println("        Properties70:  {")
        
        if (!obj.evaluationFlags.noTranslate) {
            writer.println("            P: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\",${obj.position.x},${obj.position.y},${obj.position.z}")
        }
        
        if (!obj.evaluationFlags.noRotate) {
            // Convert radians to degrees
            val rx = Math.toDegrees(obj.rotation.x.toDouble())
            val ry = Math.toDegrees(obj.rotation.y.toDouble())
            val rz = Math.toDegrees(obj.rotation.z.toDouble())
            writer.println("            P: \"Lcl Rotation\", \"Lcl Rotation\", \"\", \"A\",$rx,$ry,$rz")
        }
        
        if (!obj.evaluationFlags.noScale) {
            writer.println("            P: \"Lcl Scaling\", \"Lcl Scaling\", \"\", \"A\",${obj.scale.x},${obj.scale.y},${obj.scale.z}")
        }
        
        writer.println("        }")
        writer.println("        Shading: T")
        writer.println("        Culling: \"CullingOff\"")
        writer.println("    }")
        writer.println()
        
        // Process children
        if (!obj.evaluationFlags.breakChildTrace) {
            for (child in obj.children) {
                writeBoneModels(writer, child, boneIndices, boneIndex)
            }
        }
        
        return boneIndex
    }
    
    private fun writeAnimationCurves(
        writer: PrintWriter,
        ninjaObject: NinjaObject<*, *>,
        motion: NjMotion,
        boneIndices: Map<NinjaObject<*, *>, Int>
    ): Pair<Long, Long> {
        val boneCount = ninjaObject.boneCount()
        var curveNodeId = 4000000000L
        var curveId = 5000000000L
        
        // Map to store curve node IDs for connections
        val curveNodeIds = mutableMapOf<Pair<Int, String>, Long>()
        
        for ((boneIndex, motionData) in motion.motionData.withIndex()) {
            if (boneIndex >= boneCount) {
                break // More animation tracks than bones
            }
            
            val bone = ninjaObject.getBone(boneIndex) ?: continue
            val nodeIndex = boneIndices[bone] ?: continue
            
            for (track in motionData.tracks) {
                when (track) {
                    is NjKeyframeTrack.Position -> {
                        writeAnimationCurveNode(writer, curveNodeId, "T", nodeIndex)
                        curveNodeIds[Pair(nodeIndex, "T")] = curveNodeId
                        
                        writeCurveTriple(
                            writer,
                            curveId,
                            curveId + 1,
                            curveId + 2,
                            track.keyframes,
                            motion.interpolation,
                            "d|X", "d|Y", "d|Z"
                        )
                        
                        curveNodeId++
                        curveId += 3
                    }
                    is NjKeyframeTrack.EulerAngles -> {
                        writeAnimationCurveNode(writer, curveNodeId, "R", nodeIndex)
                        curveNodeIds[Pair(nodeIndex, "R")] = curveNodeId
                        
                        writeCurveTripleEuler(
                            writer,
                            curveId,
                            curveId + 1,
                            curveId + 2,
                            track.keyframes,
                            motion.interpolation
                        )
                        
                        curveNodeId++
                        curveId += 3
                    }
                    is NjKeyframeTrack.Scale -> {
                        writeAnimationCurveNode(writer, curveNodeId, "S", nodeIndex)
                        curveNodeIds[Pair(nodeIndex, "S")] = curveNodeId
                        
                        writeCurveTriple(
                            writer,
                            curveId,
                            curveId + 1,
                            curveId + 2,
                            track.keyframes,
                            motion.interpolation,
                            "d|X", "d|Y", "d|Z"
                        )
                        
                        curveNodeId++
                        curveId += 3
                    }
                    is NjKeyframeTrack.Quaternion -> {
                        // FBX uses Euler angles, so we would need to convert quaternions
                        // For now, skip quaternion tracks
                    }
                }
            }
        }
        
        return Pair(curveNodeId, curveId)
    }
    
    private fun writeAnimationCurveNode(
        writer: PrintWriter,
        curveNodeId: Long,
        channel: String,
        boneIndex: Int
    ) {
        writer.println("    AnimationCurveNode: $curveNodeId, \"AnimCurveNode::$channel\", \"\" {")
        writer.println("        Properties70:  {")
        writer.println("            P: \"d|X\", \"Number\", \"\", \"A\",0")
        writer.println("            P: \"d|Y\", \"Number\", \"\", \"A\",0")
        writer.println("            P: \"d|Z\", \"Number\", \"\", \"A\",0")
        writer.println("        }")
        writer.println("    }")
        writer.println()
    }
    
    private fun writeCurveTriple(
        writer: PrintWriter,
        xCurveId: Long,
        yCurveId: Long,
        zCurveId: Long,
        keyframes: List<NjKeyframe.Vector>,
        interpolation: NjInterpolation,
        xAttr: String,
        yAttr: String,
        zAttr: String
    ) {
        if (keyframes.isEmpty()) return
        
        val interpMode = when (interpolation) {
            NjInterpolation.Linear -> "L"
            NjInterpolation.Spline -> "C"
            NjInterpolation.UserFunction -> "L"
        }
        
        // X curve
        writer.println("    AnimationCurve: $xCurveId, \"AnimCurve::\", \"\" {")
        writer.println("        Default: 0")
        writer.println("        KeyVer: 4008")
        writer.println("        KeyTime: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { frameToKTime(it.frame).toString() })
        writer.println("        }")
        writer.println("        KeyValueFloat: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { it.value.x.toString() })
        writer.println("        }")
        writer.println("        KeyAttrFlags: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "8456" })
        writer.println("        }")
        writer.println("        KeyAttrDataFloat: *${keyframes.size * 4} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size * 4).joinToString(",") { "0" })
        writer.println("        }")
        writer.println("        KeyAttrRefCount: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "1" })
        writer.println("        }")
        writer.println("    }")
        writer.println()
        
        // Y curve
        writer.println("    AnimationCurve: $yCurveId, \"AnimCurve::\", \"\" {")
        writer.println("        Default: 0")
        writer.println("        KeyVer: 4008")
        writer.println("        KeyTime: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { frameToKTime(it.frame).toString() })
        writer.println("        }")
        writer.println("        KeyValueFloat: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { it.value.y.toString() })
        writer.println("        }")
        writer.println("        KeyAttrFlags: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "8456" })
        writer.println("        }")
        writer.println("        KeyAttrDataFloat: *${keyframes.size * 4} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size * 4).joinToString(",") { "0" })
        writer.println("        }")
        writer.println("        KeyAttrRefCount: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "1" })
        writer.println("        }")
        writer.println("    }")
        writer.println()
        
        // Z curve
        writer.println("    AnimationCurve: $zCurveId, \"AnimCurve::\", \"\" {")
        writer.println("        Default: 0")
        writer.println("        KeyVer: 4008")
        writer.println("        KeyTime: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { frameToKTime(it.frame).toString() })
        writer.println("        }")
        writer.println("        KeyValueFloat: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { it.value.z.toString() })
        writer.println("        }")
        writer.println("        KeyAttrFlags: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "8456" })
        writer.println("        }")
        writer.println("        KeyAttrDataFloat: *${keyframes.size * 4} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size * 4).joinToString(",") { "0" })
        writer.println("        }")
        writer.println("        KeyAttrRefCount: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "1" })
        writer.println("        }")
        writer.println("    }")
        writer.println()
    }
    
    private fun writeCurveTripleEuler(
        writer: PrintWriter,
        xCurveId: Long,
        yCurveId: Long,
        zCurveId: Long,
        keyframes: List<NjKeyframe.Vector>,
        interpolation: NjInterpolation
    ) {
        if (keyframes.isEmpty()) return
        
        val interpMode = when (interpolation) {
            NjInterpolation.Linear -> "L"
            NjInterpolation.Spline -> "C"
            NjInterpolation.UserFunction -> "L"
        }
        
        // X curve (convert radians to degrees)
        writer.println("    AnimationCurve: $xCurveId, \"AnimCurve::\", \"\" {")
        writer.println("        Default: 0")
        writer.println("        KeyVer: 4008")
        writer.println("        KeyTime: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { frameToKTime(it.frame).toString() })
        writer.println("        }")
        writer.println("        KeyValueFloat: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { Math.toDegrees(it.value.x.toDouble()).toString() })
        writer.println("        }")
        writer.println("        KeyAttrFlags: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "8456" })
        writer.println("        }")
        writer.println("        KeyAttrDataFloat: *${keyframes.size * 4} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size * 4).joinToString(",") { "0" })
        writer.println("        }")
        writer.println("        KeyAttrRefCount: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "1" })
        writer.println("        }")
        writer.println("    }")
        writer.println()
        
        // Y curve
        writer.println("    AnimationCurve: $yCurveId, \"AnimCurve::\", \"\" {")
        writer.println("        Default: 0")
        writer.println("        KeyVer: 4008")
        writer.println("        KeyTime: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { frameToKTime(it.frame).toString() })
        writer.println("        }")
        writer.println("        KeyValueFloat: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { Math.toDegrees(it.value.y.toDouble()).toString() })
        writer.println("        }")
        writer.println("        KeyAttrFlags: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "8456" })
        writer.println("        }")
        writer.println("        KeyAttrDataFloat: *${keyframes.size * 4} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size * 4).joinToString(",") { "0" })
        writer.println("        }")
        writer.println("        KeyAttrRefCount: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "1" })
        writer.println("        }")
        writer.println("    }")
        writer.println()
        
        // Z curve
        writer.println("    AnimationCurve: $zCurveId, \"AnimCurve::\", \"\" {")
        writer.println("        Default: 0")
        writer.println("        KeyVer: 4008")
        writer.println("        KeyTime: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { frameToKTime(it.frame).toString() })
        writer.println("        }")
        writer.println("        KeyValueFloat: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println(keyframes.joinToString(",") { Math.toDegrees(it.value.z.toDouble()).toString() })
        writer.println("        }")
        writer.println("        KeyAttrFlags: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "8456" })
        writer.println("        }")
        writer.println("        KeyAttrDataFloat: *${keyframes.size * 4} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size * 4).joinToString(",") { "0" })
        writer.println("        }")
        writer.println("        KeyAttrRefCount: *${keyframes.size} {")
        writer.print("            a: ")
        writer.println((0 until keyframes.size).joinToString(",") { "1" })
        writer.println("        }")
        writer.println("    }")
        writer.println()
    }
    
    private fun writeConnections(
        writer: PrintWriter,
        ninjaObject: NinjaObject<*, *>,
        motion: NjMotion,
        curveIds: Pair<Long, Long>
    ) {
        writer.println("Connections:  {")
        
        // Connect bones to their parents
        val boneIndices = mutableMapOf<NinjaObject<*, *>, Int>()
        writeBoneConnections(writer, ninjaObject, boneIndices, -1)
        
        // Connect animation stack to layer
        writer.println("    C: \"OO\",3456789012,2345678901")
        writer.println()
        
        // Connect animation curves to bones
        writeAnimationConnections(writer, ninjaObject, motion, boneIndices, curveIds.first, curveIds.second)
        
        writer.println("}")
        writer.println()
    }
    
    private fun writeBoneConnections(
        writer: PrintWriter,
        obj: NinjaObject<*, *>,
        boneIndices: MutableMap<NinjaObject<*, *>, Int>,
        parentIndex: Int
    ): Int {
        if (obj.evaluationFlags.skip) {
            for (child in obj.children) {
                writeBoneConnections(writer, child, boneIndices, parentIndex)
            }
            return parentIndex
        }
        
        val boneIndex = boneIndices.size
        boneIndices[obj] = boneIndex
        val modelId = 1000000000L + boneIndex
        
        if (parentIndex >= 0) {
            val parentModelId = 1000000000L + parentIndex
            writer.println("    C: \"OO\",$modelId,$parentModelId")
        }
        
        if (!obj.evaluationFlags.breakChildTrace) {
            for (child in obj.children) {
                writeBoneConnections(writer, child, boneIndices, boneIndex)
            }
        }
        
        return boneIndex
    }
    
    private fun writeAnimationConnections(
        writer: PrintWriter,
        ninjaObject: NinjaObject<*, *>,
        motion: NjMotion,
        boneIndices: Map<NinjaObject<*, *>, Int>,
        startCurveNodeId: Long,
        startCurveId: Long
    ) {
        val boneCount = ninjaObject.boneCount()
        var curveNodeId = startCurveNodeId
        var curveId = startCurveId
        
        for ((boneIndex, motionData) in motion.motionData.withIndex()) {
            if (boneIndex >= boneCount) {
                break
            }
            
            val bone = ninjaObject.getBone(boneIndex) ?: continue
            val nodeIndex = boneIndices[bone] ?: continue
            val modelId = 1000000000L + nodeIndex
            
            for (track in motionData.tracks) {
                when (track) {
                    is NjKeyframeTrack.Position -> {
                        // Connect curve node to bone
                        writer.println("    C: \"OP\",$curveNodeId,$modelId, \"Lcl Translation\"")
                        // Connect curve node to layer
                        writer.println("    C: \"OO\",$curveNodeId,3456789012")
                        // Connect curves to curve node
                        writer.println("    C: \"OP\",$curveId,$curveNodeId, \"d|X\"")
                        writer.println("    C: \"OP\",${curveId + 1},$curveNodeId, \"d|Y\"")
                        writer.println("    C: \"OP\",${curveId + 2},$curveNodeId, \"d|Z\"")
                        
                        curveNodeId++
                        curveId += 3
                    }
                    is NjKeyframeTrack.EulerAngles -> {
                        writer.println("    C: \"OP\",$curveNodeId,$modelId, \"Lcl Rotation\"")
                        writer.println("    C: \"OO\",$curveNodeId,3456789012")
                        writer.println("    C: \"OP\",$curveId,$curveNodeId, \"d|X\"")
                        writer.println("    C: \"OP\",${curveId + 1},$curveNodeId, \"d|Y\"")
                        writer.println("    C: \"OP\",${curveId + 2},$curveNodeId, \"d|Z\"")
                        
                        curveNodeId++
                        curveId += 3
                    }
                    is NjKeyframeTrack.Scale -> {
                        writer.println("    C: \"OP\",$curveNodeId,$modelId, \"Lcl Scaling\"")
                        writer.println("    C: \"OO\",$curveNodeId,3456789012")
                        writer.println("    C: \"OP\",$curveId,$curveNodeId, \"d|X\"")
                        writer.println("    C: \"OP\",${curveId + 1},$curveNodeId, \"d|Y\"")
                        writer.println("    C: \"OP\",${curveId + 2},$curveNodeId, \"d|Z\"")
                        
                        curveNodeId++
                        curveId += 3
                    }
                    is NjKeyframeTrack.Quaternion -> {
                        // Skip quaternion tracks for now
                    }
                }
            }
        }
    }
    
    private fun frameToKTime(frame: Int): Long {
        return (frame / PSO_FRAME_RATE * KTIME_PER_SECOND).toLong()
    }
}
